server:
  servlet:
    context-path: /v1
  port: 8080

  datasource:
    url: jdbc:postgresql://localhost:5432/recipe
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
